# Generated by Django 5.1.6 on 2025-03-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_email_cipher_user_phone_cipher_user_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='nonce',
            field=models.CharField(blank=True, null=True),
        ),
    ]
