# Generated by Django 5.1.6 on 2025-03-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chatmessage_nonce_user_email_cipher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='fileName',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='fileType',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
